[gcp_service_account]
type = "service_account"
project_id = "comment-analyzer-463511"
private_key_id = "51737bb4e537f76aade4ad9cd8eef205dc5a357a"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDTmi6zUQKnnpml
XL5Xh96baJvSxX6wUeoTqeCh4ZmA7ZVQA7EsfzKA+9memTn9LGpqAy7JS9WnyB1m
v4SU1lhlWO+xHKHsjyDzae+zWgMYCSy9sIqyTuSiTD7UIA6pbgbiZb+n4rFdkK2K
f7blggofiq7npiyqjhCd+YrU6OM8/xfYFw3rylx+2tVbNdXOkN/dZqHyvG3Twn3t
bvbIBoGqDmJqKiQnm6PY5/EcAcdbsXvBxPDs2dO0wAMiPXe7SaQIXUtm3dKawjbq
CjeKebV1+yUtk7VV6G+PkcatY2lsaRvYuFPhpt8lp367c6jmlo67aKKTelrWodNA
NijyhN6HAgMBAAECggEAKkBZHtkILKwQheJU52lr26AxrQ5eU5qnoLGE9w3y9rl5
3PY/xGDJltOzCmYSHCloPi7QgsUvrkbZCBEpygZatDHj+nt7IZ8atz/p6ugIQh5i
3qWHrD7wjC+pQ/X6t34OxdoHQOCVBdfDryn9PSqQFug8MGkP9iZTzxdqz0SJSz5P
YuIpnLi71pKNAekjCBQPLui01JeAP+W/4OsoWzEXTtlGau4SGM4p24eIsa4r6vUw
9zeieod0Ch+epEMwikGIQxKiElcw35mIlx7wTZKCNCL+GjSjNIeE8dcJtSGMZu7i
SVe8fix6KqzupQ4Q0M+jgvj6Ebq9+AdTBCAQDnkGIQKBgQDxvkytadv2GV4Bi/AB
JKq2pLxzMjCpHv6WeMgmojrDtbnDJBr9Dh7VvhCs1aBYYwnzJe8/fLci4c/iVcbi
rBXOa7VKIerqZ/N9g2WaihT05cnbKwAUihpvJrTFbmFDhDKJBy9PlzaxUoNg5SWx
hsZwdF58kLEG6SyFO8iguvK1SQKBgQDgFNSUQO/CKPPRLeBH54o62R8sfx8FeJb9
+qMcPY5YCG4HdiyiLBEyO9X4nvvK5RHhBmbRDGe8keroz97WNvPuj/ZF9IVKvagu
fdqUOjShwjYExerP13MzcTKK7Sv7kEW6/wm+afRg3IKAUSVHLHiWa7rl/L7FEHNT
+aWsjfCFTwKBgCHBP7WrJWKcsiqnHpEaTJgKMqInLPJAeK4MGW6Dko8HTfP4k6go
E5gm3O81ORl+YsJH1rtXr764Jy3kakv2WWkkUwER8Vpfv3kUItjMVRbJC0GGJJG5
ou1IS0+SFRS3XdMSZMHJTILAEcYy2OuL9SN4rETac02Su3uzGFWRJRi5AoGAMsgF
tONScmndd1YyMZljVhrGWcslOJQvg7c9J7U7gO/IH6DEVKwv6XZt8z30SfLHrntI
6a8qAy3+UmxpT5p8hV/Sq9/SJTH93yteUaEvNElS/JntsNReoxXQInPFN+lmJA6Q
IrrYSusuF+5LyGlnmo8nd99jTD2CJVG6HfS8wTkCgYEAo+63osChFNPqfCRAUN5A
cXbxX+X5UcSYmmPO6qUNfQ+Ve4xkCVQRyNxeOj9C5JqoZyAlkMzyv3ovp+VzIhMH
SO8mKXR6pVpKSuBPdFGWPfg1b5dtEDgXb2Oibl1opsFnufwUY1yc9Up1f0Sc5Rka
O4DaPe/MRzSPd5ffojjojx4=
-----END PRIVATE KEY-----"""
client_email = "builderkeyu@comment-analyzer-463511.iam.gserviceaccount.com"
client_id = "117932597619126587160"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/builderkeyu%40comment-analyzer-463511.iam.gserviceaccount.com"

[openai_api_key]
openai_api_key = "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"

[sender_email]
sender_email = "lunachpham@gmail.com"

[sender_password]
sender_password = "slghgjioniviegtz"
