[gcp_service_account]
type = "service_account"
project_id = "comment-analyzer-463511"
private_key_id = "27d1ab99d0f992145024e47eafcfe4289ef8b707"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDSwDHBs7UC2m8a
DxuF4pXC0nxSfZxc212757sWP7TdOlgC9U2G7yrqKtSbn5OF4YB2qYqd3OO0Gzpj
jSsAlJyk8TRzpUKexb/mQIRXbBpi9LwkNCfUoTOVfhWzsxsKS77WHeQ5PeG0oOTM
yY2vNHcLSWf/IQNXOls+hGhmgSiM36FRq9LUjagDjbVOnNn1lr4OndFV6iij6dKG
2IE4dqNYdM2vrcWPfkG7z26habiGrwGHxEuQl3TrDeQTuciYySnc5QdRbZI8mvim
Cu0HROnIB0Y3IuI2L7R8GaxbHciULu3lMtFKckLjAEJTI9ynT9zKybJC475G/2wk
B6ARFMQLAgMBAAECggEAIQYv5dAArc1HupgicnTijdBI3e5D+cMAKakyxlY+Q6pY
T0JcHyhMG7yRaz9ysPh4ll+T0o/h+H+Jwz7EPceL0kbftr1vNoz7OJvkgQR2EAqU
jsHDegy2lhbXVLzcoFzlLw0pDZU2UIUjxTlSI+G/Q7wBeVeVe+4vjRjXeTSFA6ng
WhIu27hNF701homTxGlHPAvaA72L3JS6DJleyOGEkfAzBZ+tIhPA4Q1O8cJBk58M
TDV2zV7eB5V+BdSU6jpUSdJXZPuw7qkLh2IgCv90pqw1Yh5GsfDwjCDVRkXuc4KV
P9fWLcWLs02Vnc7YLBQDi0JhdoiBDBZdgmpuD2QoFQKBgQD4dWzPqAWyBVrukwmG
NzhC+6i/7WfTtKJto/yOEAZvLkj7bHInmX1qi9gL2EX8P8tNDEm2Xsd4aZkcNE3S
IKBTx0y/zqRVbFQsih/w4Y2faiaAKnoqRw9GEEv0GaC/gZfYjzbVbOeG4GrdHJQG
Vj/RMOBVslorlA/QTzAcxtLarwKBgQDZJcVdV3QV2aVm5xKXIyPe9zXHsXwfQtky
H8+DeTK1CDZXjtwsTpnTcMZjvmcrmMaEILJCdkkzv21WR4gc8DUjTuBnVgmxBR/3
iSY9t8UvKrdnZsU9sX0HAT0TjXoTa1VqgT66gEFL8v8RZRD9l8qxKtu+yKbMoToH
htFxhU6TZQKBgQCHB0IwhM87lZ96oxx8/cus05o9XGed7cCMt5+NEXZ9u/jb828C
yG8ZlZC/tzUpxv3VDMWOwGnFrhYQ9vgIJ8UaYuj6IPK8nhgM8LA1OE/AgG8WHn+w
NFg/qqGssrTi/yon/oU9bmdRrOtG6b4kx4D9ToPM7xYEMv55JmAuc3uqbwKBgQCn
svDibmi7ezOu7ePAjyXjyv1gtGRMbD764/BJ8+7COo5lPnIxUZ6g2aaNX32kAL/H
SM0CYQGVkk/pYyLuXmBbXU4W4C5p5LBUZjn/Tg5dp9quY4MOayVIpJ87m3ZcyvbT
Yu9D70r+UbLFB02A25pxCs1cYO/Yducu6uKTjkUptQKBgQCNVp4pAsYU9LkadCwj
vztkLBuwgNe5bNWs3eu7jozxCP8e8eKBawqm5lQyEOscr+AcBloHCCB/JUZqVt/U
E7z56l390XDlwTAvi618BeIG02pUsjgJiseMkjn2XweRO+BcE1P2a6eKOZfawdCi
N6wNDGEt3SP4O107uM6fad5mJQ==
-----END PRIVATE KEY-----"""

client_email = "builderkeyu@comment-analyzer-463511.iam.gserviceaccount.com"
client_id = "117932597619126587160"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/builderkeyu%40comment-analyzer-463511.iam.gserviceaccount.com"

[openai_api_key]
openai_api_key = ""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""


[sender_email]
sender_email = "lunachpham@gmail.com"

[sender_password]
sender_password = "slghgjioniviegtz"


